;; -*- mode: eask; lexical-binding: t -*-

(package "f"
         "0.21.0"
         "Modern API for working with files and directories")

(website-url "https://github.com/rejeep/f.el")
(keywords "files" "directories")

(package-file "f.el")
(files "f*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'melpa)
(source 'gnu)

(depends-on "emacs" "26.1")
(depends-on "s" "1.7.0")
(depends-on "dash" "2.2.0")

(development
 (depends-on "ert-runner")
 (depends-on "ert-async")
 (depends-on "undercover"))
